version: "3"
services:
  grafana:
    image: grafana/grafana-oss:9.5.2
    container_name: grafana
    restart: always
    user: root
    ports:
      - 3000:3000
    volumes:
      - ./grafana-volume:/var/lib/grafana
      - ./grafana-config/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    logging:
      driver: loki
      options:
        loki-url: http://192.168.90.3:3100/loki/api/v1/push
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"

  loki:
    image: grafana/loki:2.8.0
    volumes:
      # - /var/log:/var/log
      - ./loki-config/loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    logging:
      driver: loki
      options:
        loki-url: http://192.168.90.3:3100/loki/api/v1/push
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"

  # promtail:
  #   image: grafana/promtail:2.8.0
  #   volumes:
  #     # - /var/log:/var/log
  #     - ./loki-config/promtail-config.yaml:/etc/promtail/config.yml
  #      - /var/lib/docker/containers:/host/containers
  #   command: -config.file /etc/promtail/config.yml
  #   logging:
  #     driver: loki
  #     options:
  #       loki-url: http://192.168.90.3:3100/loki/api/v1/push

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    logging:
      driver: loki
      options:
        loki-url: http://192.168.90.3:3100/loki/api/v1/push
        mode: non-blocking
        max-buffer-size: 4m
        loki-retries: "3"

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
   