version: "3"
services:
  elastic-agent:
    image: elastic/elastic-agent:7.17.8
    container_name: elastic-agent
    ports:
      - 8220:8220
    networks:
      - telemetry-systems
    restart: always
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    environment:
      - FLEET_SERVER_ENABLE=true
      - FLEET_SERVER_ELASTICSEARCH_HOST=http://elasticsearch:9200
      - FLEET_SERVER_ELASTICSEARCH_USERNAME=elastic
      - FLEET_SERVER_ELASTICSEARCH_PASSWORD=sgszH6qzhtycbQEtnLEU
      - FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2ODEzNTU0Mzg1NjY6T1VMMlc2X1dUeXVKVG91RVVhYjQyQQ
      - FLEET_SERVER_POLICY=499b5aa7-d214-5b5d-838b-3cd76469844e
      - FLEET_SERVER_INSECURE_HTTP=true
      - FLEET_URL= https://elastic-agent:8220
      - KIBANA_FLEET_SETUP=true
      - KIBANA_FLEET_HOST=http://kibana:5601
      - KIBANA_FLEET_USERNAME=elastic
      - KIBANA_FLEET_PASSWORD=sgszH6qzhtycbQEtnLEU
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.8
    container_name: apm-server
    networks:
      - telemetry-systems
    ports:
      - 8200:8200
    command: >
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=kibana:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=kibana:5601
         -E apm-server.kibana.username=elastic
         -E apm-server.kibana.password=sgszH6qzhtycbQEtnLEU
         -E output.elasticsearch.hosts=["elasticsearch:9200"]
         -E output.elasticsearch.username=elastic
         -E output.elasticsearch.password=sgszH6qzhtycbQEtnLEU
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

networks:
  telemetry-systems:
    external: true