version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.8
    container_name: es01
    restart: always
    networks:
      - telemetry-systems
    healthcheck:
      test: curl --fail http://localhost:9200/_cluster/health?wait_for_status=green&timeout=1s || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      # - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=false
      # - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - discovery.type=single-node
      - search.allow_expensive_queries=true
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.17.8
    container_name: kib01
    restart: always
    links:
      - "elasticsearch"
    ports:
      - 5601:5601
    networks:
      - telemetry-systems
    healthcheck:
      test: curl --fail http://localhost:5601/ || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    volumes:
      - ./conf/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  telemetry-systems:
    external: true