version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.8
    container_name: es01
    restart: always
    networks:
      - telemetry-systems
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=false
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.17.8
    container_name: kib01
    restart: always
    links:
      - "elasticsearch"
    ports:
      - 5601:5601
    networks:
      - telemetry-systems
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200

networks:
  telemetry-systems:
    external: true